### PR TITLE
Add colored wallpapers

### PR DESCRIPTION
**Pull request by ItzSwirlz**
I was bored, so I decided: Let's add some colored wallpapers!

I colored the wallpapers via the hex displayed by the README. I went into GIMP, used the Colorize tool and overwrote.

Some images asked for quality and I went with default. It will either show up as 95, or 90.

Basically, when someone installs the new theme, they get wallpapers to fit their icon style. When I tested it out on Ubuntu MATE, it looked great, but weird and not fitting as well.

An XML was created, and I also changed the descriptions to show that wallpapers are in the package.

The only thing I did not fill out is the changelog, as I didn't know how you guys wanted to sign it, if you decide to put me as the lister and you as the trailer line:

[Joshua Peisach]
* Add new colorized wallpapers/xml

or something along the lines of that.

I know that we are so far into the development and release is in T-17 days. But even if so, I hope we can at least pull this into the PPA so people will end up getting it, and in 20.10 it will work as a masterpiece :)

Let me know what you think!

### CODE REVIEW

**Comment by lah7** [comment]
Thank you very much!

Yes, we can get this implemented before release, being an _external_ feature. I've been _too_ busy with the new Ubuntu MATE website, but the thought of coloured wallpapers did twig. :art: 

---

Logic in Welcome can be trivially added to automatically switch wallpapers if any of the default ones are in use. If you're still a little bored and know a bit of Python, would you like to add this in the `ubuntu-mate-welcome-legacy` repo?

If so, just add some lines in [ubuntu-mate-welcome in the `verify_theme_status` function](https://github.com/ubuntu-mate/ubuntu-mate-welcome-legacy/blob/17e3388ef2f3609981cb370bdbad6c5d6a35f574/ubuntu-mate-welcome#L3932) checking the current background (perhaps file names) and write gconf keys as necessary.

---

In terms of storing backgrounds, I'm hoping to avoid storing them (as binaries) in version control. I appreciate preparing these involved a fair bit of manual work in GIMP, but this feature would be more valuable (flexible and easier to maintain) by generating them at build time using **Imagemagick**. This has the added bonus of working with **any** custom colour.

I'm not sure how you achieved the colourize tool in GIMP (good job!), but my understanding with that tool is that it's not 100% true to the hex. 

Here's what Imagemagick can do with the original in 2 commands:

```
convert Green-Wall.png -colorspace gray output1.png
convert output1.png -background white -fill '#2DACD4' -tint 100 output2.png
```

preview

:point_left: **Left** is yours | **Right** is one produced by Imagemagick :point_right: 

The logic for generating these (and XML) can be added to `ubuntu-mate-colours-generator`, assuming you're comfortable with Python. I'd also like to request adding `colours` suffix in the `backgrounds` folder, to keep the naming consistent across this project.

Is this something you'd be happy to do?

**Comment by ItzSwirlz** [comment]
I’ll give it a shot! Do you have a telegram account?

**Comment by lah7** [comment]
[Yep.](https://t.me/LukeHorwell)

**Comment by lah7** [comment]
@ItzSwirlz How's progress? If you _need_ to message me, I'd prefer to keep communications here [but I can be reached via the Ubuntu MATE Community](https://ubuntu-mate.community/u/lah7).

Timing wise, the beta freeze is actually **April 16th** (6 days) so the sooner the better. :ok_hand:

**Comment by ItzSwirlz** [comment]
I've been trying to figure out the python code and get the actual build and commands working, my friend is going to try to help me today (its 9:50 EST). Don't worry, I have all the dates ready, but if we can try to get this ready by the 16th, Final Freeze, then that'd be great. :)

If I have any questions, I'll DM you via discourse.

**Comment by lah7** [comment]
Good work, almost there! :+1:

Do you intend to commit the finishing touches today (April 15th) or may I continue from here so I can integrate and get it tested in time?

**Comment by ItzSwirlz** [comment]
It's been great, but right now I'm trying to deal with removing the extra source wallpapers and Grey wallpapers after the build, and then I need to deal with the XML files and I'll try to get welcome working.

**Comment by ItzSwirlz** [comment]
I just pushed. I got the builder for the XML and wallpapers working, but the Gray and Green source files aren't removed, I still need to finish the packaging, and now that we are at Final Freeze, I don't think we will be able to implement this for 20.04. Sound ok to you?

**Comment by lah7** [comment]
Since time is the essence, I'll complete the remaining changes from here. We will absolutely get this integrated for 20.04.

Thank you for your efforts.

**Comment by lah7** [comment]
I've reviewed the changes and committed the new feature in d4177ec801c2fe8e652514ebdb690ea6e7b1f2ad

I made some tweaks:

* Made changes to avoid dealing with a working directory.
* Rewrote the XML generation in Python (keeps it in one place)
* Updated parameters/paths to consider the XML folder.
* Added file/folder checks, and avoid copying the original wallpapers (seems redundant as the recoloured files are not processed in-place nor an overlay like theme/icons)

I'll package these up, and also get the logic working in Welcome.

**Comment by ItzSwirlz** [comment]
Thanks. I’m glad we could make this work :)

**Comment by lah7** [comment]
The auto switching logic for Welcome has been added in https://github.com/ubuntu-mate/ubuntu-mate-welcome-legacy/commit/9815e4878c29b95ab2be2dccfb4137234679672e. Should make its way to the beta snap (and Welcome PPA) within 24 hours.

_Whew!_ :sweat_smile: That was more logical then I thought. :jigsaw: :brain:

**Pull request merged**
